1X=20:Y=13:FORI=0TO9:IFI=5THENPLOTX+I,Y+I+1,"*":PLOTX+I,Y+I+2,"*":PLOTX+I+1,Y+I,"**":PLOTX+I,Y-I-1,"*":PLOTX+I,Y-I-2,"*":PLOTX+I+1,Y-I,"**":PLOTX-I,Y+I+1,"*":PLOTX-I,Y+I+2,"*":PLOTX-I-2,Y+I,"**":PLOTX-I,Y-I-1,"*":PLOTX-I,Y-I-2,"*":PLOTX-I-2,Y-I,"**"
5IFI<>7ANDI<>4THEN8
6PLOTX+I,Y+1,"*":PLOTX+I,Y-1,"*":PLOTX-I,Y+1,"*":PLOTX-I,Y-1,"*":PLOTX+I+1,Y+2,"*":PLOTX+I+1,Y-2,"*":PLOTX-I-1,Y+2,"*":PLOTX-I-1,Y-2,"*"
7PLOTX+1,Y+I,"*":PLOTX-1,Y+I,"*":PLOTX+1,Y-I,"*":PLOTX-1,Y-I,"*":PLOTX+2,Y+I+1,"*":PLOTX-2,Y+I+1,"*":PLOTX+2,Y-I-1,"*":PLOTX-2,Y-I-1,"*"
8IFI<8THENPLOTX+I,Y+I,"*":PLOTX-I,Y+I,"*":PLOTX+I,Y-I,"*":PLOTX-I,Y-I,"*"
9PLOTX+I,Y,"*":PLOTX-I,Y,"*":PLOTX,Y+I,"*":PLOTX,Y-I,"*":NEXT